# Generated by Django 5.1.4 on 2026-05-01 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Фото (завантажити)')),
                ('image_static', models.CharField(blank=True, help_text='Напр.: img/gallery/fk-1.png — використовується якщо не завантажено фото.', max_length=200, verbose_name='Шлях до статичного фото (fallback)')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt текст')),
                ('caption', models.CharField(max_length=200, verbose_name='Підпис під фото')),
                ('lightbox_caption', models.CharField(blank=True, max_length=200, verbose_name='Підпис Lightbox')),
                ('badge_label', models.CharField(blank=True, max_length=20, verbose_name='Мітка бейджу')),
                ('badge_colour', models.CharField(choices=[('default', 'Синій'), ('green', 'Зелений'), ('amber', 'Жовтий'), ('brown', 'Коричневий')], default='default', max_length=20, verbose_name='Колір бейджу')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видима')),
            ],
            options={
                'verbose_name': 'Фото галереї',
                'verbose_name_plural': 'Галерея',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Код (ФК / ФСФ / ДВП…)')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('badge_colour', models.CharField(choices=[('default', 'Синій'), ('green', 'Зелений'), ('amber', 'Жовтий'), ('brown', 'Коричневий')], default='default', max_length=20, verbose_name='Колір бейджу')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото (завантажити)')),
                ('image_static', models.CharField(blank=True, help_text='Напр.: img/products/fk.png — використовується якщо не завантажено фото.', max_length=200, verbose_name='Шлях до статичного фото (fallback)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимий')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_name', models.CharField(default='ФОП Музичко М.В.', max_length=100, verbose_name='Назва компанії')),
                ('header_tagline', models.CharField(default='Фанера · ДВП · ДСП', max_length=100, verbose_name='Підзаголовок хедера')),
                ('header_phone', models.CharField(default='+380976962409', help_text='Формат: +380976962409', max_length=30, verbose_name='Телефон хедера (для посилання tel:)')),
                ('hero_title', models.CharField(default='Будівельні плити та фанера у Рівному', max_length=200, verbose_name='Заголовок Hero')),
                ('hero_subtitle', models.CharField(default='Гурт та роздріб з 1997 року · Індивідуальні ціни', max_length=300, verbose_name='Підзаголовок Hero')),
                ('about_year', models.CharField(default='1997', max_length=10, verbose_name='Рік заснування')),
                ('about_experience', models.CharField(default='28+', max_length=10, verbose_name='Років досвіду')),
                ('about_product_count', models.CharField(default='4', max_length=10, verbose_name='Видів продукції')),
                ('about_text_1', models.TextField(default='', verbose_name='Текст «Про нас» 1')),
                ('about_text_2', models.TextField(default='', verbose_name='Текст «Про нас» 2')),
                ('cta_title', models.CharField(default='Готові до співпраці?', max_length=200, verbose_name='CTA заголовок')),
                ('cta_description', models.CharField(default='Розкажіть про вашу потребу — підберемо оптимальну позицію та ціну', max_length=300, verbose_name='CTA опис')),
                ('contact_address', models.CharField(default='вул. Будівельників, 7, м. Рівне', max_length=200, verbose_name='Адреса')),
                ('contact_phone_1', models.CharField(default='+380976962409', help_text='Формат: +380976962409', max_length=30, verbose_name='Телефон 1 (для посилання tel:)')),
                ('contact_phone_1_display', models.CharField(default='097 696 24 09', max_length=30, verbose_name='Телефон 1 (відображення)')),
                ('contact_phone_2', models.CharField(default='+380505072334', help_text='Формат: +380505072334', max_length=30, verbose_name='Телефон 2 (для посилання tel:)')),
                ('contact_phone_2_display', models.CharField(default='050 507 23 34', max_length=30, verbose_name='Телефон 2 (відображення)')),
                ('contact_email', models.EmailField(default='', max_length=254, verbose_name='E-mail')),
                ('contact_cta_title', models.CharField(default='Готові до співпраці', max_length=100, verbose_name='Заголовок CTA-контактів')),
                ('footer_copyright', models.CharField(default='ФОП Музичко Михайло Васильович · Рівне', max_length=200, verbose_name='Текст копірайту (без року)')),
                ('meta_description', models.CharField(default='', max_length=300, verbose_name='Meta description')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Характеристика')),
                ('value', models.TextField(verbose_name='Значення')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='core.product')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'ordering': ['order'],
            },
        ),
    ]
