# Generated by Django 5.1.4 on 2026-05-07 10:23

from django.db import migrations, models


def fix_brand_text(apps, schema_editor):
    SiteSettings = apps.get_model("core", "SiteSettings")
    obj = SiteSettings.objects.filter(pk=1).first()
    if not obj:
        return
    old_headers = ("ФАНЕРА  ДВП", "ФАНЕРА ДВП", "ФОП Музичко М.В.", "Фанері")
    hn = (obj.header_name or "").strip()
    if hn in old_headers:
        obj.header_name = "Фанери"
    elif "Фанері" in hn:
        obj.header_name = hn.replace("Фанері", "Фанери")
    fc = obj.footer_copyright or ""
    if "ФАНЕРА  ДВП" in fc:
        obj.footer_copyright = fc.replace("ФАНЕРА  ДВП", "Фанери")
    if "Фанері" in fc:
        obj.footer_copyright = fc.replace("Фанері", "Фанери")
    md = obj.meta_description or ""
    if "ФАНЕРА  ДВП" in md:
        obj.meta_description = md.replace("ФАНЕРА  ДВП", "Фанери")
    if "Фанері" in md:
        obj.meta_description = md.replace("Фанері", "Фанери")
    obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_update_brand_name'),
    ]

    operations = [
        migrations.RunPython(fix_brand_text, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_copyright',
            field=models.CharField(default='Фанери · Рівне', max_length=200, verbose_name='Текст копірайту (без року)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='header_name',
            field=models.CharField(default='Фанери', max_length=100, verbose_name='Назва компанії'),
        ),
    ]
